### ISSUE TITLE
Unable to Load Cart Drop-in Component

### ISSUE THREAD

**Issue by RoshanTekno** [hlxsites/aem-boilerplate-commerce#232]
**Description**  
I’m trying to use the `@dropins/storefront-cart` drop-in component, and I’ve followed the steps outlined in the documentation. However, I encounter the following error when attempting to load the component:

```
failed to load module for commerce-cart SyntaxError: The requested module '@dropins/tools/lib.js' does not provide an export named 'merge' (at getStoreConfig.js:3:124)
```

Here is my `commerce-cart.js` file for reference:

```javascript
/* eslint-disable import/no-unresolved */
/* eslint-disable import/no-extraneous-dependencies */
// GraphQL Client

// component tools
import { initializers } from "@dropins/tools/initializer.js";

// drop-in component functions
import * as pkg from "@dropins/storefront-cart/api.js";

// Drop-in component provider
import { render as provider } from "@dropins/storefront-cart/render.js";

// Drop-in component containers
import Cart from "@dropins/storefront-cart/containers/Cart.js";

// Libs
import { fetchPlaceholders } from "../../scripts/aem.js";

import { getConfigValue } from "../../scripts/configs.js";

export default async function decorate(block) {
  const [placeholders] = await Promise.all([fetchPlaceholders()]);

  const langDefinitions = {
    default: {
      ...placeholders,
    },
  };

  // Set Fetch Endpoint (Service)
  pkg.setEndpoint(await getConfigValue("commerce-core-endpoint"));

  // Initialize Dropins
  initializers.register(pkg.initialize, {
    langDefinitions,
  });

  // Render Containers
  return new Promise((resolve) => {
    setTimeout(async () => {
      try {
        await provider.render(Cart, {
          slots: {
            ProductList: (ctx) => {
              // title decoration
              const tagline = document.createElement("div");
              tagline.classList.add("title-decoration");
              tagline.innerHTML = "WKND Essentials";
              ctx.prependSibling(tagline);

              const rating = document.createElement("div");
              rating.classList.add("ratings");
              rating.innerHTML = "⭐️⭐️⭐️⭐️⭐️";
              ctx.appendSibling(rating);
            },
          },
          useACDL: true,
        })(block);
      } catch (e) {
        console.error(e);
        await loadErrorPage();
      } finally {
        resolve();
      }
    }, 0);
  });
}
```

---

**Steps to Reproduce**  
1. Implement the above code in a `commerce-cart.js` file.
2. Run the application.
3. Attempt to render the `@dropins/storefront-cart` component.
4. Observe the console error.

---

**Expected Behavior**  
The cart drop-in component should render as expected without any errors.

---

**Observed Behavior**  
The application throws a syntax error:  
```
failed to load module for commerce-cart SyntaxError: The requested module '@dropins/tools/lib.js' does not provide an export named 'merge' (at getStoreConfig.js:3:124)
```

---

**Environment**  
- **Node.js version**: 20
- **Package version**: 0.10.0
- **Browser**: Chrome
- **Operating System**: Windows

---

**Additional Context**  
It seems the `@dropins/tools/lib.js` module may be missing an expected export or there might be an issue with my usage/imports. If I’m doing something wrong with the imports or initialization, please let me know.

Looking forward to your guidance. Thank you!

**Comment by fnhipster** [comment]
@RoshanTekno, are you using `main` or `develop` branch in your project? Either way, make sure you are using `@dropins/tools` version `0.36.0` in your `package.json`

**Comment by RoshanTekno** [comment]
Hi @fnhipster thank you for your help forking the develop branch worked like wonder.
